loki:
  enabled: true
  persistence: 
    enabled: true
    storageClassName: standard

promtail:
  enabled: true

prometheus:
  enabled: true

grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: true
  image:
    tag: 9.1.0

